apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: kro-apps
data:
  init-db.sql: |
    CREATE TABLE IF NOT EXISTS submissions (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
