# kro-formapp-access-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: formapp-writer-binding
subjects:
  - kind: ServiceAccount
    name: api-access
    namespace: default
roleRef:
  kind: ClusterRole
  name: formapp-writer
  apiGroup: rbac.authorization.k8s.io
