# formapp-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: formapps.kro.run
spec:
  group: kro.run
  names:
    kind: FormApp
    listKind: FormAppList
    plural: formapps
    singular: formapp
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                name:
                  type: string
                app:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    name:
                      type: string
                    image:
                      type: string
                    replicas:
                      type: integer
                      default: 2
                    port:
                      type: integer
                      default: 8086
                    service:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: ["ClusterIP", "NodePort", "LoadBalancer", "ExternalName"]
                          default: "LoadBalancer"
                database:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                    name:
                      type: string
                    image:
                      type: string
                      default: "bitnami/postgresql:12.1.0"
                    dbName:
                      type: string
                      default: "formdb"
                    username:
                      type: string
                      default: "postgres"
                    password:
                      type: string
                      default: "postgres"
                    port:
                      type: integer
                      default: 5432
                    storage:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: true
                        storageClass:
                          type: string
                          default: "longhorn"
                        size:
                          type: string
                          default: "5Gi"
                        accessMode:
                          type: string
                          enum: ["ReadWriteOnce", "ReadOnlyMany", "ReadWriteMany"]
                          default: "ReadWriteOnce"
                ingress:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: false

