apiVersion: kro.run/v1alpha1
kind: FormApp
metadata:
  name: form-app-instance
  namespace: kro-apps
spec:
  name: form-app
  image: moses101/form-app:latest
  db: false
  ingress:
    enabled: false

