# formapp-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: formapps.kro.run
spec:
  group: kro.run
  names:
    kind: FormApp
    listKind: FormAppList
    plural: formapps
    singular: formapp
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                db:
                  type: boolean
                isApp:
                  type: boolean
                isDb:
                  type: boolean
                ingress:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                service:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: ["ClusterIP", "NodePort", "LoadBalancer", "ExternalName"]
                      default: "ClusterIP"
                storage:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: false
                    storageClass:
                      type: string
                      default: "longhorn"
                    size:
                      type: string
                      default: "1Gi"
                    accessMode:
                      type: string
                      enum: ["ReadWriteOnce", "ReadOnlyMany", "ReadWriteMany"]
                      default: "ReadWriteOnce"
                securityContext:
                  type: object
                  properties:
                    fsGroup:
                      type: integer
                      default: 1001                
