apiVersion: kro.run/v1alpha1
kind: FormApp
metadata:
  name: postgres-db-instance
  namespace: kro-apps
spec:
  name: postgres
  image: bitnami/postgresql:12.1.0
  db: true
  isDb: true
  isApp: false
  ingress:
    enabled: false
  storage:
    enabled: true
    storageClass: longhorn
    size: 5Gi
    accessMode: ReadWriteOnce
  securityContext:
    fsGroup: 1001
    runAsUser: 1001
    runAsGroup: 1001
  initContainer:
    enabled: true
    image: busybox
    command: 
      - chown
      - "-R"
      - "1001:1001"
      - "/bitnami/postgresql/data"
    mountPath: "/bitnami/postgresql/data"