apiVersion: kro.run/v1alpha1
kind: FormApp
metadata:
  name: postgres-db-instance
  namespace: kro-apps
spec:
  name: postgres
  image: bitnami/postgresql:12.1.0
  db: true
  isDb: true
  isApp: false
  ingress:
    enabled: false
