apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: metallb-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: speaker
  namespace: metallb-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-system:controller
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metallb.io"]
    resources: ["ipaddresspools", "l2advertisements", "bgpadvertisements", "bgppeers", "bfdprofiles"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["metallb.io"]
    resources: ["ipaddresspools/status", "l2advertisements/status", "bgpadvertisements/status", "bgppeers/status", "bfdprofiles/status"]
    verbs: ["update"]
  - apiGroups: ["metallb.io"]
    resources: ["bgpadvertisements"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-system:speaker
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metallb.io"]
    resources: ["ipaddresspools", "l2advertisements", "bgpadvertisements", "bgppeers", "bfdprofiles"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-system:controller
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: metallb-system
roleRef:
  kind: ClusterRole
  name: metallb-system:controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-system:speaker
subjects:
  - kind: ServiceAccount
    name: speaker
    namespace: metallb-system
roleRef:
  kind: ClusterRole
  name: metallb-system:speaker
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metallb
    component: controller
  name: controller
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
      component: controller
  template:
    metadata:
      labels:
        app: metallb
        component: controller
    spec:
      serviceAccountName: controller
      containers:
        - name: controller
          image: quay.io/metallb/controller:v0.14.3
          args:
            - --port=7472
          ports:
            - containerPort: 7472
              name: webhook
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7472
          readinessProbe:
            httpGet:
              path: /healthz
              port: 7472
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: metallb
    component: speaker
  name: speaker
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app: metallb
      component: speaker
  template:
    metadata:
      labels:
        app: metallb
        component: speaker
    spec:
      serviceAccountName: speaker
      containers:
        - name: speaker
          image: quay.io/metallb/speaker:v0.14.3
          args:
            - --port=7472
          env:
            - name: METALLB_ML_BIND_ADDR
              value: "0.0.0.0"
          ports:
            - containerPort: 7472
              name: metrics
          securityContext:
            capabilities:
              add: ["NET_RAW", "NET_ADMIN"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7472
          readinessProbe:
            httpGet:
              path: /healthz
              port: 7472
