apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: form-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/youruser/form-submission-app.git
    targetRevision: HEAD
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: kro-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true