name: Docker Build and Push

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push from app/
        uses: docker/build-push-action@v5
        with:
          context: ./app                # 👈 app directory as build context
          file: ./app/Dockerfile        # 👈 use Dockerfile inside app/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/form-app:latest
